### ISSUE TITLE
Kale uploaded pipeline run with ModuleNotFoundError error in k8s kubeflow

### ISSUE THREAD

**Issue by IvySong2016** [kubeflow-kale/kale#105]
I tried to use kale to convert the notebook titanic_dataset_ml to pipelines in my k8s kubeflow, the pipelines uploaded successfully, but the **loaddata** part is failed with the following error:
‘’‘
_Traceback (most recent call last):
  File "<string>", line 59, in <module>
  File "<string>", line 16, in loaddata
ModuleNotFoundError: No module named 'seaborn'_
’‘’
I guess that is because i **did not enable** 'Use this notebook's volumes' , I don't know why i can not enable it in my k8s kubeflow, is it because the pvc I used had no storageclass? Is there any way to install the missed python package 'seaborn'?

**Comment by StefanoFioravanzo** [comment]
@IvySong2016 Please see related issue #72

**Comment by IvySong2016** [comment]
Here is the snapshot of the error:
<img src="https://github.com/IvySong2016/issue_snapshots/blob/master/kale_loaddata_issue1.png?raw=true" >

Here is the snapshot of the Kale Deployment Panel and the selected icon can not be enabled:
<img src="https://github.com/IvySong2016/issue_snapshots/blob/master/kale_deployment_panel.png?raw=true" >

**Comment by StefanoFioravanzo** [comment]
@IvySong2016 you need to be running on MiniKF to have that toggle working. MiniKF ships with Rok, a data management platform that can take snapshots of your volumes. Kale will detect if the Rok is available and enable that toggle

**Comment by yaliqin** [comment]
> Here is the snapshot of the error:
> ![](https://github.com/IvySong2016/issue_snapshots/blob/master/kale_loaddata_issue1.png?raw=true)
> 
> Here is the snapshot of the Kale Deployment Panel and the selected icon can not be enabled:
> ![](https://github.com/IvySong2016/issue_snapshots/blob/master/kale_deployment_panel.png?raw=true)

I solved this problem by manually mounting two pv to same path.

**Comment by sensor2sensor** [comment]
@yaliqin 
Can I know your steps?
 
Thanks
