### ISSUE TITLE
Titanic Example: FileNotFoundError

### ISSUE THREAD

**Issue by jhaanuj2108** [kubeflow-kale/kale#133]
Hi, I have created my own docker file for serving Kale in the jupyter lab (Link to docker file: https://hub.docker.com/r/jhaanuj2108/kaleimage). The Kale Deployment Panel is working fine, and the code for titanic provided in examples is running fine in jupyter lab but while running the pipeline it throws an error. (FYI: I have copied the CSV files from the data folder to the folder where my code snippet/ipynb file is present because it was not working the other way too.)

![Screenshot (31)](https://user-images.githubusercontent.com/29893565/82866170-034b1200-9f46-11ea-83a2-b7c1f016fd12.png)

![Screenshot (30)](https://user-images.githubusercontent.com/29893565/82866168-0219e500-9f46-11ea-97a5-bb62c6d8c7f6.png)

![image](https://user-images.githubusercontent.com/29893565/82866413-79e80f80-9f46-11ea-8336-0a921cb337fd.png)

**Comment by yaliqin** [comment]
@jhaanuj2108 I met the same problem, how did you solve it?

**Comment by jhaanuj2108** [comment]
I found out after having a talk in slack that, Kubeflow's pipeline requires PVC access which I didn't understand completely. But to solve the problem I tried downloading it directly instead of storing and reading.

```
path = "/home/jovyan/"
PREDICTION_LABEL = 'Survived'
url1 = 'https://raw.githubusercontent.com/kubeflow-kale/examples/master/titanic-ml-dataset/data/test.csv'
url2 = 'https://raw.githubusercontent.com/kubeflow-kale/examples/master/titanic-ml-dataset/data/train.csv'
print("getting files")
urllib.request.urlretrieve(url1, path + "test.csv")
urllib.request.urlretrieve(url2, path + "train.csv")
print("reading files")
test_df = pd.read_csv(path + "test.csv")
train_df = pd.read_csv(path + "train.csv")
```

**Comment by yaliqin** [comment]
Thank you!! Could you tell me which slack channel? I want to add too. Where did you execute above code, in the notebooks server terminal or the pod of pipeline. Sorry, I am quite new to this area, may ask very simple question.

**Comment by jhaanuj2108** [comment]
Hey, even I am very new to this thing and I hace received lot of support from the community, so I am just forwarding the help. Here is the link to the slack: https://kubeflow.slack.com/. Here you will get response almost everytime and that too very quick. 
Coming to the point of executing the code, you must do it from the notebook server itself where you are running your code. Replace the code that reads csv from some path with what I have given. You might have to make some changes to the path accordingly. I am assuming that you are using kale for pipeline, so when you run this code it should work directly in your notebook and the pipeline.

**Comment by yaliqin** [comment]
Thank you!!
I found there is no way to mount the pv of our namespace to the pv of
kubeflow. But I can't change the setting.  So I need to ask directly in
that channel. But it seems the account should be registered to that
channel, could you tell me how to do that?

**Comment by jhaanuj2108** [comment]
Go to slack and then you can register there. They will ask for organization name so insert Kubeflow and they will ask for your mail id and all. Do that and you will be able to access the slack as well as the channels inside it.

**Comment by yaliqin** [comment]
Thank you!  I

**Comment by tbala2805** [comment]
> Hi, I have created my own docker file for serving Kale in the jupyter lab (Link to docker file: https://hub.docker.com/r/jhaanuj2108/kaleimage). The Kale Deployment Panel is working fine, and the code for titanic provided in examples is running fine in jupyter lab but while running the pipeline it throws an error. (FYI: I have copied the CSV files from the data folder to the folder where my code snippet/ipynb file is present because it was not working the other way too.)
> 
> ![Screenshot (31)](https://user-images.githubusercontent.com/29893565/82866170-034b1200-9f46-11ea-83a2-b7c1f016fd12.png)
> 
> ![Screenshot (30)](https://user-images.githubusercontent.com/29893565/82866168-0219e500-9f46-11ea-97a5-bb62c6d8c7f6.png)
> 
> ![image](https://user-images.githubusercontent.com/29893565/82866413-79e80f80-9f46-11ea-8336-0a921cb337fd.png)

Hi,
Bala this side doing MLOps work with help of kubeflow,(working on one simple linear regression model.
I am having the same problem though I have the CSV file in the desired location. note:  i am not using the kale  image of while creating the notebook server . kindly help

Error: CSV file not found error .

Actions done:
Change the file name
Replaced the forward backward slash viceversa 
Used double slashes
And assign separe variable for the path 
Still can't resolve.

**Comment by tbala2805** [comment]
Hi,
Bala this side doing MLOps work with help of kubeflow,(working on one simple linear regression model.
I am having the same problem though I have the CSV file in the desired location. note:  i am not using the kale  image of while creating the notebook server . kindly help

Error: CSV file not found error .

Actions done:
Change the file name
Replaced the forward backward slash viceversa 
Used double slashes
And assign separe variable for the path 
Still can't resolve.

**Comment by tbala2805** [comment]
Quit urgent
