### ISSUE TITLE
add_node_selector_constraint with Kale

### ISSUE THREAD

**Issue by ivsanro1** [kubeflow-kale/kale#138]
Hello,

I would like to specify that one component (pipeline step) has to be run in a specified node of the cluster. This can be achieved by doing op.add_node_selector_constraint when working with kfp.dsl directly, but I would like to know if there is an automatic way of declaring it with Kale.

If there is not, I guess I have to manually edit either the .py file that generates the yaml of the pipeline, or edit the yaml directly, but none of this cases is optimal.

Also, if there is not, do you have any plans of adding this feture in the future? Maybe as an extra option when declaring the cell metadata in JupyterLab?

Thank you

**Comment by StefanoFioravanzo** [comment]
Hi @ivsanro1 Yes we are planning to bring this feature to Jupyter in the feature. You will notice (if you build from `master`) that we support settings GPU limits on a per-step basis. We will extend this to support any kind of limit/label/selectors that will be applied to individual steps

**Comment by ivsanro1** [comment]
Thanks! Can't wait for the new version 👍

**Comment by marcel-steinbach-mpf** [comment]
@StefanoFioravanzo does it make sense to reopen this to address support for a more generic version of `add_node_selector_constraint`?
