### ISSUE TITLE
"!pip install " embedding can't be compiled to pipeline

### ISSUE THREAD

**Issue by yaliqin** [kubeflow-kale/kale#142]
When I ran the titanic example on the Kubeflow deployed on K8s cluster, I met the seaborn, pandas and sklearn module not found problem during compile and run the pipeline phase. I solved this problem by add the pip install command in my notebook server docker file. I think these three libraries are quite common and can be built to the image. But when I run Taxicab example, "apache_beam" module isn't installed. I think this module isn't common and not a good choice to install it in the docker file. So I added "!pip3 install apache_beam --user" in the .jupyter file. Running this line in the notebook server is successful. But when I tried to compile and run the pipeline, this line can't been parsed.  The error message is,
"An RPC Error has occurred
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

Type: RPC

Method: nb.compile_notebook()

Code: 6 (UnhandledError)

Transaction ID: s514h7chi8

Message: invalid syntax (<unknown>, line 53)

Details: You can find more information under /home/jovyan/kale.log"

When I view the kale.log, it is said,
"Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/run.py", line 92, in run
    result = func(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/nb.py", line 61, in compile_notebook
    pipeline_graph, pipeline_parameters = instance.notebook_to_graph()
  File "/usr/local/lib/python3.6/dist-packages/kale/core.py", line 231, in notebook_to_graph
    ignore_symbols=set(pipeline_parameters_dict.keys()))
  File "/usr/local/lib/python3.6/dist-packages/kale/static_analysis/dep_analysis.py", line 61, in variables_dependencies_detection
    all_names = inspector.get_all_names(block_data['source'])
  File "/usr/local/lib/python3.6/dist-packages/kale/static_analysis/inspector.py", line 193, in get_all_names
    tree = ast.parse(code)
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    !pip3 install apache_beam --user
    ^
SyntaxError: invalid syntax"

Is there any way other than adding all the install library commands to the docker file?

**Comment by ivsanro1** [comment]
I think that the best you can do here is build your own Dockerfile FROM the one you are using to setup the JupyterLab where you are running the notebook and RUN whatever you need to install all your dependencies, then create a JupyterLab server with those dependencies already installed.

If you don't want to create a new JupyterLab server, you can create this Docker Image and specify it it in the pipeline that Kale generates, but I recomment the first option.

**Comment by StefanoFioravanzo** [comment]
Hello @yaliqin  Indeed currently Kale does not support running `!` notebook commands in the KFP pipeline. In the coming Kale release we are starting to improve on this by first supporting Jupyter magic commands (this is already in `master`) and in the near future we will also expand this to support `!` commands.

For now, I think you can try using python's `subprocess` module to run CLI commands form your python code.

**Comment by yaliqin** [comment]
Thank you @StefanoFioravanzo and @ivsanro1  for the reply. I will try those methods in my project.

**Comment by yaliqin** [comment]
I found in the new example of dog breed, there are ! notebook commands used. Does it mean it is supported to be compiled to Pipeline?

**Comment by StefanoFioravanzo** [comment]
Hi @yaliqin , those commands are currently being tagged with the `skip` tag. They are meant to be run in your notebook server (e.g. for downloading data or installing dependencies), not in the pipeline step

**Comment by yaliqin** [comment]
@StefanoFioravanzo Got it! Thanks.
