### ISSUE TITLE
cannot import name 'mlmd_utils' from 'kale.utils'

### ISSUE THREAD

**Issue by robertmujica** [kubeflow-kale/kale#147]
All,

just noticed, when i generate pipeline on latest kale 0.5.0 using following command:

kale --nb xxx.ipynb --kfp_host 'hostname/pipeline' --pipeline_name <pipeline name> --upload_pipeline --run_pipeline --experiment_name <experiment name>

experiment failed with following error:

Traceback (most recent call last):
  File "<string>", line 188, in <module>
  File "<string>", line 2, in data_import
ImportError: cannot import name 'mlmd_utils' from 'kale.utils' (/opt/conda/lib/python3.7/site-packages/kale/utils/__init__.py)

if i switch back to kubeflow-kale==0.4.0, it works ok.

is this a known / reported issue ?

**Comment by elikatsis** [comment]
Hi @robertmujica,

Pipeline steps need to be using a docker image with Kale installed. The package in this image needs to have the same version with the CLI you use to generate the pipeline.

Could it be that you are using some old notebook configuration (with an older docker image with a different Kale version)?
Could you check the `metadata.kubeflow_notebook.docker_image` key in your `xxx.ipynb` file? (you can open it using a text editor, e.g., `vim`, and see it as a JSON)

**Comment by robertmujica** [comment]
@elikatsis Bingo I'm 99% sure we are using old kale version in our Docker image, so that would explain the why it works when i use old version ( which i believe match the one on image )

I'm going to close this issue.

Thanks for your response.
