### ISSUE TITLE
Configurable storageClass name

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow-kale/kale#161]
It would be great if from the UI you could configure the storageClass name used for the marshall.
At present it will use the cluster default, e.g. "standard" which causes issues if you have set up a new storageClass say for NFS in your cluster.

**Comment by StefanoFioravanzo** [comment]
Hi @cliveseldon this is something that is definitely feasible. We are planning to revamp the "Volumes" UI in the Kale sidebar and, when that will happen, we will keep in mind this aspect as well. Thanks for feedback! Of course, contributions are always welcome :)
