### ISSUE TITLE
Incorrect input shape of train_ResNet50 in Dog Breed Classification example

### ISSUE THREAD

**Issue by jainvi-wwt** [kubeflow-kale/kale#184]
In step 5 (CNN-ResNet50) of the Dog Breed Classification example, the input shape of the ResNet50_model is expected to be (None, 1, 1, 2048), which is the shape of train_ResNet50, loaded from 'bottleneck_features/DogResnet50Data.npz'. However, during prediction, the input shape of the tensor is (None, 7, 7, 2048), which leads to an error.

**Comment by dpoulopoulos** [comment]
Hello,

Could you provide more info on this? Have you altered the code of the example or run it as it is? Could you share the code snippets where you create the model and train it?

**Comment by jainvi-wwt** [comment]
I am working on the dog-breed.ipynb notebook. I have run the code as it is (with some additional print steps for clarity). I have not run the wget steps in the beginning.

This image shows that the shape of train_ResNet50 loaded from bottleneck_features is (30, 1, 1, 2048).
![image](https://user-images.githubusercontent.com/68677069/92576197-d9282080-f2a6-11ea-9c72-26e43c6cb9a9.png)

In the prediction step, I get the following warning:
![image](https://user-images.githubusercontent.com/68677069/92582260-5a36e600-f2ae-11ea-8721-bc611ae0e819.png)
![image](https://user-images.githubusercontent.com/68677069/92582294-66bb3e80-f2ae-11ea-91d9-a0905a2f8c03.png)

The warning says that the Model was constructed with shape (None, 1, 1, 2048), but we are giving it an input with incompatible shape (None, 7, 7, 2048). This is followed by ValueError: Input 0 of layer dense_2 is incompatible with the layer: expected axis -1 of input shape to have value 2048 but received input with shape [None, 100352].

**Comment by dpoulopoulos** [comment]
Could you tell us the version of Keras and TensorFlow you use to run this? Also, where do you run the notebook (locally, on the cloud)? And can you provide the complete stack trace?

**Comment by jainvi-wwt** [comment]
Versions used:
Keras==2.4.3
tensorflow==2.3.0

I am running the notebook in a Jupyterlab environment on a notebook server (created using a custom Docker image - _jainviwwt/kale-tf-2.1.0:cpu_v2.2_) using Kubeflow on AWS.

Here is the complete stack trace (including Warnings):
> WARNING:tensorflow:7 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f58c87450d0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Test bottleneck features shape: (1, 7, 7, 2048)
WARNING:tensorflow:Model was constructed with shape (None, 1, 1, 2048) for input Tensor("flatten_input:0", shape=(None, 1, 1, 2048), dtype=float32), but it was called on an input with incompatible shape (None, 7, 7, 2048).
---------------------------------------------------------------------------

> ValueError                                Traceback (most recent call last)
> <ipython-input-38-73ce535e149f> in <module>
>      17 gtruth = np.argmax(test_targets[0])
>      18 gtruth = dog_names[gtruth].split('.')[-1]
> ---> 19 pred = predict_breed(img_path)
>      20 print("Groundtruth dog breed: {}".format(gtruth))
>      21 print("Predicted dog breed: {}".format(pred))
> 
> <ipython-input-38-73ce535e149f> in predict_breed(img_path)
>       3     bottleneck_feature = ebf.extract_Resnet50(img)
>       4     print('Test bottleneck features shape:', bottleneck_feature.shape)
> ----> 5     predicted = ResNet50_model.predict(bottleneck_feature)
>       6     idx = np.argmax(predicted)
>       7     return dog_names[idx].split('.')[-1]
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
>     128       raise ValueError('{} is not supported in multi-worker mode.'.format(
>     129           method.__name__))
> --> 130     return method(self, *args, **kwargs)
>     131 
>     132   return tf_decorator.make_decorator(
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
>    1597           for step in data_handler.steps():
>    1598             callbacks.on_predict_batch_begin(step)
> -> 1599             tmp_batch_outputs = predict_function(iterator)
>    1600             if data_handler.should_sync:
>    1601               context.async_wait()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
>     778       else:
>     779         compiler = "nonXla"
> --> 780         result = self._call(*args, **kwds)
>     781 
>     782       new_tracing_count = self._get_tracing_count()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
>     812       # In this case we have not created variables on the first call. So we can
>     813       # run the first trace but we should fail if variables are created.
> --> 814       results = self._stateful_fn(*args, **kwds)
>     815       if self._created_variables:
>     816         raise ValueError("Creating variables on a non-first call to a function"
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
>    2826     """Calls a graph function specialized to the inputs."""
>    2827     with self._lock:
> -> 2828       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
>    2829     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
>    2830 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
>    3208           and self.input_signature is None
>    3209           and call_context_key in self._function_cache.missed):
> -> 3210         return self._define_function_with_shape_relaxation(args, kwargs)
>    3211 
>    3212       self._function_cache.missed.add(call_context_key)
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _define_function_with_shape_relaxation(self, args, kwargs)
>    3140 
>    3141     graph_function = self._create_graph_function(
> -> 3142         args, kwargs, override_flat_arg_shapes=relaxed_arg_shapes)
>    3143     self._function_cache.arg_relaxed[rank_only_cache_key] = graph_function
>    3144 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
>    3073             arg_names=arg_names,
>    3074             override_flat_arg_shapes=override_flat_arg_shapes,
> -> 3075             capture_by_value=self._capture_by_value),
>    3076         self._function_attributes,
>    3077         function_spec=self.function_spec,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
>     984         _, original_func = tf_decorator.unwrap(python_func)
>     985 
> --> 986       func_outputs = python_func(*func_args, **func_kwargs)
>     987 
>     988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
>     598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
>     599         # the function a weak reference to itself to avoid a reference cycle.
> --> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
>     601     weak_wrapped_fn = weakref.ref(wrapped_fn)
>     602 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
>     971           except Exception as e:  # pylint:disable=broad-except
>     972             if hasattr(e, "ag_error_metadata"):
> --> 973               raise e.ag_error_metadata.to_exception(e)
>     974             else:
>     975               raise
> 
> ValueError: in user code:
> 
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1462 predict_function  *
>         return step_function(self, iterator)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1452 step_function  **
>         outputs = model.distribute_strategy.run(run_step, args=(data,))
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
>         return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
>         return self._call_for_each_replica(fn, args, kwargs)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
>         return fn(*args, **kwargs)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1445 run_step  **
>         outputs = model.predict_step(data)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1418 predict_step
>         return self(x, training=False)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:985 __call__
>         outputs = call_fn(inputs, *args, **kwargs)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:372 call
>         return super(Sequential, self).call(inputs, training=training, mask=mask)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:386 call
>         inputs, training=training, mask=mask)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:508 _run_internal_graph
>         outputs = node.layer(*args, **kwargs)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:976 __call__
>         self.name)
>     /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_spec.py:216 assert_input_compatibility
>         ' but received input with shape ' + str(shape))
> 
>     ValueError: Input 0 of layer dense_2 is incompatible with the layer: expected axis -1 of input shape to have value 2048 but received input with shape [None, 100352]

**Comment by dpoulopoulos** [comment]
It's important to use Keras 2.0.2 for this example to work. The `keras.applications.resnet50` architecture is restructured in later versions, thus the extracted features differ in shape. The ResNet-50 architecture in Keras `2.4.3` has the following output layer (if you set `include_top=False`):

```
conv5_block3_out (Activation)   (None, 7, 7, 2048)   0           conv5_block3_add[0][0]
```

But Keras `2.0.2` has this as the last output layer:

```
avg_pool (AveragePooling2D)      (None, 1, 1, 2048)    0 
```

This is what causes the missmatch.

I suggest to either downgrade or run the `dog-breed-v2.ipynb` example, updated for TensorFlow `2.3.0`. You might need to `git pull` to get the latest commits.
