### ISSUE TITLE
Support Python 3.7 and 3.8 and kfp 1.0.0

### ISSUE THREAD

**Issue by ksonbol** [kubeflow-kale/kale#189]
Hello,

I was only able to install kale with python 3.6.3 and it installed kfp 0.3.0 as a requirement which is quite outdated now.

With Python 3.7.7, there is this dependency conflict:
`kfp 0.3.0 requires kfp-server-api<0.4.0,>=0.2.5, but you'll have kfp-server-api 0.1.18.3 which is incompatible`.

With Python 3.8, it is not possible to install it because of the `ml-metadata` dependency which isn't upgraded to support python 3.8 yet.

**Comment by StefanoFioravanzo** [comment]
Hu @ksonbol can you try installing from `master`? We have removed the limiting kfp dependency but haven't release a new version yet

**Comment by DavidSpek** [comment]
ml-metadata v0.24.0 was released 2 days ago with support for python 3.8. 
https://github.com/google/ml-metadata/releases/tag/v0.24.0

**Comment by DavidSpek** [comment]
@ksonbol Python 3.8 is now compatible, along with KFP 1.0.0. Can you confirm this issue is resolved for you?

**Comment by ksonbol** [comment]
Thank you @DavidSpek . I can confirm that building from master works fine. Looking forward to the coming release :)

**Comment by DavidSpek** [comment]
I believe this issue can be closed in that case.
