### ISSUE TITLE
Serving model

### ISSUE THREAD

**Issue by rikardocorp** [kubeflow-kale/kale#195]
How can I serve a kale-trained model with kfserving?

**Comment by Benniah** [comment]
I am also facing this issue .

**Comment by Benniah** [comment]
Turns out it’s now possible to Serve with this approach . Here is a link : 
https://tinyurl.com/yxsvektu

**Comment by StefanoFioravanzo** [comment]
Thanks @Benniah for sharing the link to our Codelab! @rikardocorp I hope you will find it interesting. Closing this issue for now

**Comment by kakawinwin** [comment]
> Turns out it’s now possible to Serve with this approach . Here is a link to an End to End deployment with Serving :
> https://tinyurl.com/yxsvektu

Hi Benniah, the link is unavailable now.

**Comment by kakawinwin** [comment]
> Turns out it’s now possible to Serve with this approach . Here is a link to an End to End deployment with Serving :
> https://tinyurl.com/yxsvektu

Hi @Benniah , the link is unavailable now.

**Comment by StefanoFioravanzo** [comment]
@kakawinwin can you double check? The link works for me. Anyway, this is the direct link http://codelabs.arrikto.com/codelabs/minikf-kale-katib-kfserving/index.html?index=..%2F..index#0
