### ISSUE TITLE
setup.py needs to be updated

### ISSUE THREAD

**Issue by robertmujica** [kubeflow-kale/kale#196]
Trying to setup this project on my machine i got few errors then i saw this line, so i remove those dependencies and oahla setup works fine, so i believe these two lines are not needed anymore as pull request #60 is already merged

# XXX: remove this once https://github.com/google/ml-metadata/pull/60
# is merged.
#'grpcio >= 1.8.6',
#'ml_metadata == 0.23.0',

happy to raise a PR to fix it.

**Comment by StefanoFioravanzo** [comment]
Hi @robertmujica what error did you experience before removing those lines?
`ml-metadata` *is* a Kale dependency that we use in the pipeline steps. Installing `grpcio` is still requires, as `ml_metadata` version `0.23.1` has yet to be released.

**Comment by robertmujica** [comment]
this is the error that i'm getting, when i run:  pip3 install -e .[dev] from backend/
..........
 Using cached https://files.pythonhosted.org/packages/ea/41/130df5822c73e42815250683634828c69449225ae61fc14f5b13884c2898/kfp-1.0.0.tar.gz
Collecting ml_metadata==0.23.0 (from kubeflow-kale==0.5.0)
  Could not find a version that satisfies the requirement ml_metadata==0.23.0 (from kubeflow-kale==0.5.0) (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0, 0.13.2)
No matching distribution found for ml_metadata==0.23.0 (from kubeflow-kale==0.5.0)

then if run tests after, i'm getting
..........
env/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
backend/kale/tests/e2e/test_e2e.py:20: in <module>
    from kale.core import Kale
E   ModuleNotFoundError: No module named 'kale'
=========================== short test summary inf0= ==============================

so i commented those lines and ran test again and i got 131 tests passed that is the reason i assumed it was not needed.
.........
kale/tests/e2e/test_e2e.py::test_pipeline_generation_from_gtihub
kale/tests/e2e/test_e2e.py::test_pipeline_generation_from_gtihub
kale/tests/e2e/test_e2e.py::test_pipeline_generation_from_gtihub
  <unknown>:26: DeprecationWarning: invalid escape sequence \.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================== 131 passed, 19 warnings in 11.95s =======================

**Comment by StefanoFioravanzo** [comment]
@robertmujica According to https://pypi.org/project/ml-metadata/0.23.0/ that version does exist. What system are you running on? Do you have some `pip` configuration that points to other package indexes maybe?

**Comment by robertmujica** [comment]
@StefanoFioravanzo no i don't have any pre-defined pip configuration, and also i created a new fresh python environment, but you are right it is a valid package, when i do a pip install manually it works ok. so like i said before, project is running on my machine and i can debug extension and on my local jupyterlab, so closing this issue
