### ISSUE TITLE
Kale lab extension fails to parse volume settings when compiling a new notebook

### ISSUE THREAD

**Issue by yoavhalevi** [kubeflow-kale/kale#220]
Hi,

I'm using kubeflow-kale==0.5.0 with the lab extension and I have encountered the issue described in the subject - whenever I create a new notebook, adding the volume from kale's lab extension and compiling the notebook, for some reason the volume isn't parsed\part of the compilation, therefore it doesnt exist in the `.py` file.

any ideas why does this happen and how to overcome it?

**Comment by DavidSpek** [comment]
Do you have an error output you can share? Have you tried running the created pipeline? Regarding `the volume isn't parsed\part of the compilation`, do you mean the volume can be found in the pipeline.py file that is created or something else?

**Comment by palmoreck** [comment]
Hi @DavidSpek I'm facing similar issue but in version `0.5.1` although in version `0.5.0` i had no problems

Please see next screenshot using `0.5.0` 

![Captura de pantalla 2020-10-13 a las 5 21 30 p m](https://user-images.githubusercontent.com/3290689/95922413-dc686d80-0d78-11eb-9090-f87610649e09.png)

And next using `0.5.1`

![Captura de pantalla 2020-10-13 a las 5 20 53 p m](https://user-images.githubusercontent.com/3290689/95922422-e2f6e500-0d78-11eb-87ef-f43871c79f5b.png)


You can see in both that in Kale Deployment Panel I'm filling Volumes section identically

This is the way I'm installing `kubeflow-kale` `0.5.1` version: [Dockerfile#L30](https://github.com/CONABIO/kube_sipecam/blob/master/dockerfiles/hsi/0.5.1/Dockerfile#L30)

Do you know what could be?

Cheers

**Comment by palmoreck** [comment]
Just for reference: I solved it changing some lines in [Dockerfile](https://github.com/CONABIO/kube_sipecam/blob/master/dockerfiles/hsi/0.5.1/Dockerfile)

![Captura de pantalla 2020-10-15 a las 1 15 58 p m](https://user-images.githubusercontent.com/3290689/96170501-4b64d400-0ee9-11eb-8916-cc501756d0e2.png)

:)

Cheers

**Comment by elikatsis** [comment]
@palmoreck, so what was the issue?
Your links point to `master` so I don't understand what the fix contains.
Is this some fault on our end? Could it be that your `docker build` cached some steps and you ended up with different backend/labextension versions?

**Comment by palmoreck** [comment]
Hey @elikatsis 

I confirm that it was something related with `docker build` ... not sure exactly what and maybe what you suggest @elikatsis 

I tested my old [Dockerfile](https://github.com/CONABIO/kube_sipecam/blob/bdce8f205f24792802cd9763b47337cb2ff7c974/dockerfiles/hsi/0.5.1/Dockerfile) and had no problems:

![Captura de pantalla 2020-10-16 a las 12 11 41 p m](https://user-images.githubusercontent.com/3290689/96288387-f5effc00-0fa8-11eb-8864-09460bd51679.png)

**Comment by elikatsis** [comment]
Good to hear! Closing the issue then.
