### ISSUE TITLE
As a User, i would like to use IPython %%Cell & %Lines with Kale.

### ISSUE THREAD

**Issue by julioyildo** [kubeflow-kale/kale#225]
Hello,

It would be a very useful to integrate IPython Magics Cells & Line.
Currently we have developed our proper magics cells for our Data Science workflow and Today we could hardly do without it.
We are very interested by Kubeflow but without Magic Cells it would be difficult for us to adopte it.

In my side, I have tried this line but i'm reaching this issue in Kale logs.
```
  File "<unknown>", line 1
    %pwd
    ^
SyntaxError: invalid syntax
```

Could you please tell me if IPython Magic cells would be integrated soon ?

Thank you !

**Comment by prashanthb-ai** [comment]
Curious if you have a use case that wouldn't be solved by a lib function that calls subprocess instead? (i.e `lib.shell("pwd")` instead of `%pwd`)
