### ISSUE TITLE
setup.py needs to be updated (2)

### ISSUE THREAD

**Issue by palmoreck** [kubeflow-kale/kale#226]
Hi there. First of all, thanks for this awesome project, simplifies a lot of work! 

I'm creating this issue with the same name as https://github.com/kubeflow-kale/kale/issues/196 because when I install `kubeflow-kale` via `pip3` I'm getting:

```
ERROR: Could not find a version that satisfies the requirement ml-metadata==0.23.0 (from kubeflow-kale==0.5.1) (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0, 0.24.0)
ERROR: No matching distribution found for ml-metadata==0.23.0 (from kubeflow-kale==0.5.1)
```

I was thinking that this was related to [announcement-pip-20-2-release/4863](https://discuss.python.org/t/announcement-pip-20-2-release/4863) or [use-feature-2020-resolver](https://stackoverflow.com/questions/63277123/what-is-use-feature-2020-resolver-error-message-with-jupyter-installation-on)

But when I downloaded `kubeflow-kale`: [kubeflow-kale-0.5.1.tar.gz](https://files.pythonhosted.org/packages/71/ca/a54a21d890c3aee82216f0b5bab79b66b15498ba8cd700266101f7574dbd/kubeflow-kale-0.5.1.tar.gz) from: [pypi.org/project/kubeflow-kale/0.5.1](https://pypi.org/project/kubeflow-kale/0.5.1/#files) and uncompressed `tar.gz` in `setup.py` there's  `ml_metadata == 0.23.0`:

```
  install_requires=[
        'kfp',
        'autopep8 >=1.4, <1.5',
        'astor >= 0.8.1',
        'nbformat >=4.4, <5.0',
        'networkx >=2.3, <3.0',
        'jinja2 >=2.10, <3.0',
        'graphviz >=0.13, <1.0',
        'pyflakes >=2.1.1',
        'dill >=0.3, <0.4',
        'IPython >= 7.6.0',
        'jupyter-client >= 5.3.4',
        'jupyter-core >= 4.6.0',
        'nbconvert >= 5.6.1, < 6.0.0',
        'ipykernel >= 5.1.4',
        'packaging > 20',
        # XXX: remove this once https://github.com/google/ml-metadata/pull/60
        # is merged.
        'grpcio >= 1.8.6',
        'ml_metadata == 0.23.0',
    ],
    extras_require={
....
```

Cheers

**Comment by palmoreck** [comment]
p.d. to reproduce this you can use this [Dockerfile](https://github.com/CONABIO/kube_sipecam/blob/master/dockerfiles/hsi/0.5.1/Dockerfile) It stops with error in [line 28](https://github.com/CONABIO/kube_sipecam/blob/master/dockerfiles/hsi/0.5.1/Dockerfile#L28)

**Comment by DavidSpek** [comment]
ml_metadata has already been updated in the master branch. Please try installing from there as it should solve your issue.

**Comment by palmoreck** [comment]
Ok, thanks. I'm closing this.
