### ISSUE TITLE
Authorization ( RBAC) issue in deploying kale pipeline with kubeflow deployed on kubernetes on-prem cluster

### ISSUE THREAD

**Issue by HariKunapareddy** [kubeflow-kale/kale#244]
Hi,

We are trying to integrate kale with kubeflow , which is deployed on-prem  kubernetes cluster with out any authentication . From the kubeflow created a notebook server with the docker image "gcr.io/arrikto/jupyter-kale:v0.5.0-47-g2427cc9" . I can see kale is integrated but when running the kale pipeline getting the below exception.

**Note:** kubeflow API doesn't have any authorisation.

**Exception on UI:** 
Type: RPC

Method: kfp.list_experiments()

Code: 6 (UnhandledError)

Transaction ID: hzlnrdbjd1

Message: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Wed, 21 Oct 2020 09:51:41 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: RBAC: access denied

Details: You can find more information under /home/jovyan/kale.log

**Attached kale.log**

2020-10-21 08:36:50 run:125 [[ERROR]] [TID=7wiujdvk7h] [/home/jovyan/Untitled.ipynb] RPC function 'upload_pipeline' raised an unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/run.py", line 116, in run
    result = func(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kale/rpc/kfp.py", line 96, in upload_pipeline
    pipeline = client.upload_pipeline(pipeline_package_path, pipeline_name)
  File "/usr/local/lib/python3.6/dist-packages/kfp/_client.py", line 692, in upload_pipeline
    response = self._upload_api.upload_pipeline(pipeline_package_path, name=pipeline_name, description=description)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 56, in upload_pipeline
    (data) = self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 139, in upload_pipeline_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 373, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/rest.py", line 275, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
kfp_server_api.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Wed, 21 Oct 2020 08:36:50 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '2'})
HTTP response body: RBAC: access denied

any one facing this?

**Comment by lomori** [comment]
Oh, I have been looking into it for a couple of days and it's driving me crazy! I kept looking into the standard Kubernetes RBAC and couldn't find any issues. Even tried to give the default-editor service account full access to all apis ('*') and still faced the same problem. I finally tracked that down to ServiceRole and ServiceRoleBinding (Istio resources). I've tried adding kubeflow to the ClusterRbacConfig installed by Kubeflow and it went past that exception. Of course, now I'm getting another one :(

But this is a hack and probably opened all sorts of security issues. DO NOT DO IT IN PRODUCTION, at least until this is investigated and a proper solution is put in place.

apiVersion: rbac.istio.io/v1alpha1
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  exclusion:
    namespaces:
    - istio-system
    - kubeflow
    - admin
  mode: ON_WITH_EXCLUSION

**Comment by elikatsis** [comment]
Hi @HariKunapareddy and @lomori!

I believe this is duplicate of #204, so I'll copy what I said there:

>Unfortunately, we are not aware of an open source deployment configuration that enables the usage of KFP client (there are multiple open issues in the KFP repo).
Even if you overcome the (Istio) RBAC issue you are bumping into, you won't be able to get properly authenticated and authorized.
>
>We, as Arrikto, have made some modifications and support it, but that's for our Enterprise deployments.

You can take a look at #204 and see how others have worked around this problem. However, as mentioned in the other issue, we don't advise you to follow the same path because it is not secure.

That said, I will close this issue. Of course, feel free to reopen.

**Comment by lomori** [comment]
@elikatsis : thanks for your reply, I sincerely appreciated it. Certainly not directed at you, and maybe to nobody in particular, but this royally sux. And that is the tip of the iceberg. I've been evaluating and until recently very helpful that we could potentially use Kubeflow at our University and Healthcare divisions, but it is coming to a point where I can't really push for it with a clean conscience. Just can't.
