### ISSUE TITLE
Cannot install kubeflow-kale due to missing ml-metadata 0.23.1

### ISSUE THREAD

**Issue by berndverst** [kubeflow-kale/kale#269]
`pip install kubeflow-kale`

```
ERROR: Could not find a version that satisfies the requirement ml-metadata==0.23.0 (from kubeflow-kale) (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0, 0.24.0, 0.25.0, 0.25.1)
ERROR: No matching distribution found for ml-metadata==0.23.0 (from kubeflow-kale)
```
This is on Python 3.8.6 in Ubuntu 20.04.1 LTS (WSL2)

I see https://github.com/kubeflow-kale/kale/blob/master/backend/setup.py#L51 is specifying 0.24.0

Did someone forget to push a new version to PyPI?

**Comment by berndverst** [comment]
@StefanoFioravanzo version 0.5.1 (latest) on PyPI still seems to require ml-metadata 0.23.0 even though setup.py for the backend specifies 0.24.0.

Can you release a new version to PyPI please?

**Comment by saltazaur** [comment]
Hi,
I'm having the same issue as @berndverst 
I'm trying to create a docker image with PyTorch, CV libraries and Kale.

**Comment by berndverst** [comment]
I posted this issue in the Kubeflow Pipelines Slack channel and tagged @StefanoFioravanzo. Hopefully we'll get more attention.

**Comment by StefanoFioravanzo** [comment]
@berndverst @saltazaur Thanks for reporting this and sorry for the delay in reply. We were planning to have a release soon, I will try to have it out today

**Comment by StefanoFioravanzo** [comment]
Hey guys, we release 0.6! Enjoy :)

**Comment by gbrlins** [comment]
Hi @StefanoFioravanzo !

Besides the new 0.6 version, setup.py is still referencing ml_metadata==0.24.0
