### ISSUE TITLE
docker image create error :: AttributeError: module 'enum' has no attribute 'IntFlag' 

### ISSUE THREAD

**Issue by pratyushpanda** [kubeflow-kale/kale#274]
Hi Team. I am using the Dockerfile listed to create a custom docker image but it fails with below error:
AttributeError: module 'enum' has no attribute 'IntFlag'

Docker image create output below

**log:
(base) mymac:kubeflow-kale p.panda$ docker build -t kubeflow-kale .
Sending build context to Docker daemon  6.144kB
Step 1/12 : ARG IMAGE_TYPE="cpu"
Step 2/12 : FROM gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-${IMAGE_TYPE}:v0.7.0
 ---> cd3b7b30dbd2
Step 3/12 : USER root
 ---> Using cache
 ---> 3f2df44cbf44
Step 4/12 : RUN apt-get update &&     apt-get install -y --no-install-recommends         ca-certificates bash-completion tar less         python-pip python-setuptools build-essential python-dev         python3-pip python3-wheel &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 01d3e144ee72
Step 5/12 : ENV SHELL /bin/bash
 ---> Using cache
 ---> e7b1cf5c115b
Step 6/12 : COPY bashrc /etc/bash.bashrc
 ---> Using cache
 ---> 9efe90da2770
Step 7/12 : RUN echo "set background=dark" >> /etc/vim/vimrc.local
 ---> Using cache
 ---> 5ffcc9ff10d2
Step 8/12 : RUN pip3 install --upgrade pip &&     pip3 install --upgrade "jupyterlab>=2.0.0,<3.0.0" &&     pip3 install https://storage.googleapis.com/ml-pipeline/release/latest/kfp.tar.gz --upgrade &&     pip3 install -U kubeflow-kale &&     jupyter labextension install kubeflow-kale-labextension
 ---> Running in 08d420206b81
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d69d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 19.1.1
    Uninstalling pip-19.1.1:
      Successfully uninstalled pip-19.1.1
Successfully installed pip-20.3.3
Collecting jupyterlab<3.0.0,>=2.0.0
  Downloading jupyterlab-2.2.9-py3-none-any.whl (7.9 MB)
Requirement already satisfied: jinja2>=2.10 in /usr/local/lib/python3.6/dist-packages (from jupyterlab<3.0.0,>=2.0.0) (2.10.1)
Requirement already satisfied: tornado!=6.0.0,!=6.0.1,!=6.0.2 in /usr/local/lib/python3.6/dist-packages (from jupyterlab<3.0.0,>=2.0.0) (5.1.1)
Requirement already satisfied: notebook>=4.3.1 in /usr/local/lib/python3.6/dist-packages (from jupyterlab<3.0.0,>=2.0.0) (5.7.8)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2>=2.10->jupyterlab<3.0.0,>=2.0.0) (1.1.1)
Collecting jupyterlab-server<2.0,>=1.1.5
  Downloading jupyterlab_server-1.2.0-py3-none-any.whl (29 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (2.22.0)
Requirement already satisfied: jsonschema>=3.0.1 in /usr/local/lib/python3.6/dist-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (3.0.1)
Requirement already satisfied: json5 in /usr/local/lib/python3.6/dist-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (0.8.5)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/dist-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (0.15.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (41.0.1)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3/dist-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (1.11.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (19.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (4.4.0)
Requirement already satisfied: jupyter-client>=5.2.0 in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (5.2.4)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (5.5.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.8.2)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.7.1)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (4.3.2)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (5.1.1)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.2.0)
Requirement already satisfied: jupyter-core>=4.4.0 in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (4.5.0)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (1.5.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.6/dist-packages (from notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (18.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from jupyter-client>=5.2.0->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (2.8.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.6/dist-packages (from terminado>=0.8.1->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.6.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (4.4.0)
Requirement already satisfied: ipython>=5.0.0 in /usr/local/lib/python3.6/dist-packages (from ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (7.5.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (2.4.2)
Requirement already satisfied: pexpect in /usr/local/lib/python3.6/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (4.7.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.6/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.1.0)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.6/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.13.3)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (2.0.9)
Requirement already satisfied: parso>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.4.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.1.7)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.3)
Requirement already satisfied: mistune>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.8.4)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.4.2)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.6.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (1.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (3.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab<3.0.0,>=2.0.0) (0.5.1)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab<3.0.0,>=2.0.0) (3.0.4)
Installing collected packages: jupyterlab-server, jupyterlab
  Attempting uninstall: jupyterlab-server
    Found existing installation: jupyterlab-server 1.0.6
    Uninstalling jupyterlab-server-1.0.6:
      Successfully uninstalled jupyterlab-server-1.0.6
  Attempting uninstall: jupyterlab
    Found existing installation: jupyterlab 1.1.4
    Uninstalling jupyterlab-1.1.4:
      Successfully uninstalled jupyterlab-1.1.4
Successfully installed jupyterlab-2.2.9 jupyterlab-server-1.2.0
Collecting https://storage.googleapis.com/ml-pipeline/release/latest/kfp.tar.gz
  Downloading https://storage.googleapis.com/ml-pipeline/release/latest/kfp.tar.gz (165 kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (5.1.2)
Requirement already satisfied: google-cloud-storage>=1.13.0 in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (1.20.0)
Requirement already satisfied: kubernetes<12.0.0,>=8.0.0 in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (10.0.1)
Requirement already satisfied: google-auth>=1.6.1 in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (1.6.3)
Requirement already satisfied: requests_toolbelt>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (0.9.1)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (1.2.2)
Requirement already satisfied: jsonschema>=3.0.1 in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (3.0.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (0.8.3)
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from kfp==1.2.0) (7.0)
Collecting docstring-parser>=0.7.3
  Downloading docstring_parser-0.7.3.tar.gz (13 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  _ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_lzndjix/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/usr/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/usr/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'_**
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_lzndjix/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
The command '/bin/bash -c pip3 install --upgrade pip &&     pip3 install --upgrade "jupyterlab>=2.0.0,<3.0.0" &&     pip3 install https://storage.googleapis.com/ml-pipeline/release/latest/kfp.tar.gz --upgrade &&     pip3 install -U kubeflow-kale &&     jupyter labextension install kubeflow-kale-labextension' returned a non-zero code: 1

**Comment by pratyushpanda** [comment]
This issue seems to be avoided by adding below to the Dockerfile
pip3 install "enum34==1.1.8"

**Comment by nachogarciam** [comment]
I can build the image using the 0.5.1 version of kubeflow-kale

**Comment by pratyushpanda** [comment]
@nachogarciam yeah. please check issue #275. i have created a bug for that.

**Comment by StefanoFioravanzo** [comment]
@pratyushpanda  This issue should be resolved by the referenced commit
