### ISSUE TITLE
Installing Kale Python Package causes dependency issues

### ISSUE THREAD

**Issue by Stythek** [kubeflow-kale/kale#281]
### Problem

I wanted to create a custom image that includes `kubeflow-kale` and other packages as well as additional JupyterLab extensions.
I am not able to install kubeflow-kale because it causes the package installer (`pip `or `pipenv`) to error due to unresolvable dependencies.

### Steps to Reproduce

1. Create a Dockerfile which installs at least the package `'kubeflow-kale==0.6.0'` using `pip`/`pipenv`.
2. Run `docker build`.

### Output

The following output is produced by `pipenv `during the creation of the `Pipfile.lock`, I shortened some information:

```
#10 194.2 ERROR: Could not find a version that matches kubernetes<12.0.0,>=11.0.0,>=12.0.0,>=8.0.0 (from kubeflow-kale==0.6.0->-r )
#10 194.2 Tried: [1.0.0 - 9.0.1], 10.0.0, 10.0.0, 10.0.1, 10.0.1, 10.1.0, 10.1.0, 11.0.0, 11.0.0, 12.0.0, 12.0.0, 12.0.1, 12.0.1
#10 194.2 Skipped pre-versions: [0.0.0a2 - 17.14.0a1]
#10 194.2 There are incompatible versions in the resolved dependencies:
#10 194.2   kubernetes<12.0.0,>=8.0.0 (from kfp==1.3.0->kubeflow-kale==0.6.0->-r )
#10 194.2   kubernetes>=11.0.0 (from kubeflow-kale==0.6.0->-r )
#10 194.2   kubernetes>=12.0.0 (from kfserving==0.5.0->kubeflow-kale==0.6.0->-r )
```

### Question

`kfserving<0.5.0` requires `kubernetes<11.0.0`, therefore is it possible to lower the required `kfserving` version as well as the `kubernetes` version requirements by `kubeflow-kale` itself?

**Comment by elikatsis** [comment]
Hi @Stythek,

We have probably fixed this issue with this PR: https://github.com/kubeflow-kale/kale/pull/277
However, we haven't produced a new release and that's why you're hitting it.

Could you try installing Kale from `master` branch? Then, if it works for you, we can close this issue.

**Comment by StefanoFioravanzo** [comment]
Hi @Stythek you should now be able to install Kale using `pip`, we have release version `0.6.1` which includes #277

**Comment by Stythek** [comment]
Hi @elikatsis and @StefanoFioravanzo
Sorry for the late response. I installed from master and the dependencies issues were resolved. We ran into some other problems along the way because of which I wasn't able to complete the tests.
Thanks for the new release!
