### ISSUE TITLE
while pip installing kubeflow-kale=0.6.0 it is downloading all the kfp packages and getting error at kfp==0.1.23.1

### ISSUE THREAD

**Issue by PeddnadePradeep** [kubeflow-kale/kale#285]
Collecting kfp
  Using cached kfp-1.3.0.tar.gz (170 kB)
  Using cached kfp-1.2.0.tar.gz (165 kB)
  Using cached kfp-1.1.2.tar.gz (159 kB)
  Using cached kfp-1.1.1.tar.gz (162 kB)
  Using cached kfp-1.1.0.tar.gz (172 kB)
  Using cached kfp-1.0.4.tar.gz (116 kB)
  Using cached kfp-1.0.3.tar.gz (116 kB)
  Using cached kfp-1.0.1.tar.gz (116 kB)
  Using cached kfp-1.0.0.tar.gz (116 kB)
  Using cached kfp-0.5.1.tar.gz (119 kB)
  Using cached kfp-0.5.0.tar.gz (118 kB)
  Using cached kfp-0.4.0.tar.gz (118 kB)
  Using cached kfp-0.3.0.tar.gz (117 kB)
  Using cached kfp-0.2.5.tar.gz (116 kB)
  Using cached kfp-0.2.4.1.tar.gz (112 kB)
  Using cached kfp-0.2.4.tar.gz (115 kB)
  Using cached kfp-0.2.2.1.tar.gz (112 kB)
  Using cached kfp-0.2.2.tar.gz (114 kB)
  Using cached kfp-0.2.1.tar.gz (112 kB)
  Using cached kfp-0.2.0.tar.gz (112 kB)
  Downloading kfp-0.1.40.tar.gz (112 kB)
     |████████████████████████████████| 112 kB 4.2 MB/s 
  Using cached kfp-0.1.39.tar.gz (112 kB)
  Using cached kfp-0.1.38.tar.gz (112 kB)
  Using cached kfp-0.1.37.tar.gz (111 kB)
  Using cached kfp-0.1.36.tar.gz (111 kB)
  Using cached kfp-0.1.35.tar.gz (105 kB)
  Using cached kfp-0.1.34.tar.gz (104 kB)
  Using cached kfp-0.1.33.tar.gz (103 kB)
  Using cached kfp-0.1.32.2.tar.gz (101 kB)
  Using cached kfp-0.1.32.1.tar.gz (100 kB)
  Using cached kfp-0.1.32.tar.gz (102 kB)
  Using cached kfp-0.1.31.2.tar.gz (99 kB)
  Using cached kfp-0.1.31.1.tar.gz (97 kB)
  Using cached kfp-0.1.31.tar.gz (94 kB)
  Using cached kfp-0.1.30.tar.gz (88 kB)
  Using cached kfp-0.1.29.tar.gz (88 kB)
  Using cached kfp-0.1.27.tar.gz (80 kB)
  Using cached kfp-0.1.26.tar.gz (81 kB)
  Using cached kfp-0.1.25.tar.gz (76 kB)
  Using cached kfp-0.1.24.tar.gz (74 kB)
  Using cached kfp-0.1.23.1.tar.gz (73 kB)
ERROR: Requested kfp from https://files.pythonhosted.org/packages/8a/58/0a69e1adc106130eb893f49874f8c193caa6310e924fddc9a701db569431/kfp-0.1.23.1.tar.gz#sha256=fa460258d2b06837e29ff41fb78e56bab4f2e7af6fb5d288e19a5ff7e91c0de0 (from kubeflow-kale==0.6.0) has different version in metadata: '0.1.23'

**Comment by StefanoFioravanzo** [comment]
Hi @PeddnadePradeep we just release version `0.6.1` which should fix your issue.
