### ISSUE TITLE
Automatic Volume detection and Snapshot

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow-kale/kale#3]
To streamline the deployment of a Pipeline when working in MiniKF, it would be great to automate the process of snapshotting the volumes used in the current Notebook Server, retrieve the associated ROK URL and use this information to mount the snapshots in the pipeline steps.

In this way the use does not have to worry about manually creating snapshots and adding Volumes entries in the Jupyter Kale UI.

Proposed execution steps:

1. Use `kubectl` to query the pods in the current namespace and retrieve the necessary volume mounts
2. Use ROK APIs to snapshot these volumes
3. Retrieve ROK URLs for the created snapshots
4. Make Kale create VolumesOps using rok annotation from step 3.

This code snipped in Python retrieves the Volume mounts of the current running Notebok Server:

```python
import os
import json
import subprocess

pod_name = os.getenv("HOSTNAME")
container_name = os.getenv("NB_PREFIX").split('/')[-1]
home = os.getenv("HOME")

def getProcessOutput(cmd):
    process = subprocess.Popen(
        cmd,
        shell=True,
        stdout=subprocess.PIPE)
    process.wait()
    data, err = process.communicate()
    if process.returncode is 0:
        return data.decode('utf-8')
    else:
        print("Error:", err)
    return ""

pods = json.loads(getProcessOutput("kubectl get pods -o json"))

pod_spec = list(filter(lambda x: x['metadata']['name'] == pod_name, pods['items']))[0]['spec']
container_spec = list(filter(lambda x: x['name'] == container_name, pod_spec['containers']))
current_docker_image = container_spec[0]['image']
current_volume_mounts = container_spec[0]['volumeMounts']
```

**Potential Issues**

We are interested in snapshotting just the volumes mounted by the use (i.e. Workspace, Data volumes). We need a way to recognize these in the list of volumeMounts. When using MiniKF this could be easy, as the server name is a substring of the volume names of interest. But his might not be the case when not using MiniKF.

**Comment by elikatsis** [comment]
I think we have this covered.

Closing it and, of course, feel free to reopen.
