### ISSUE TITLE
Container creating

### ISSUE THREAD

**Issue by Soot3** [kubeflow-kale/kale#314]
Good day. Is there an update on this error. I'm running microk8s on gcp and the pipeline stalls on the first component with the Container creating error.

I have tried changing RWM - RWO from the notebook server as well as the compiled .py file. It still ends with this error, using the 0.5. image and the rok workshop one.

Any help available?

**Comment by elikatsis** [comment]
Hi @Soot3 ,

could you provide some more information? What's the error? Are there any logs or screenshots you can show?
What's the images you have tried? What is the KF version deployed in microk8s? What's the KFP version?

**Comment by Soot3** [comment]
I have used this gcr.io/arrikto/jupyter-kale:v0.5.0 and gcr.io/arrikto-public/tensorflow-1.14.0-notebook-cpu:kubecon-workshop. Kubeflow v1.0. Kfp 0.3.0. 


![Screenshot (453)](https://user-images.githubusercontent.com/53571625/109021622-5875a900-76bb-11eb-8219-20c2e1ec77eb.png)


![Screenshot (452)](https://user-images.githubusercontent.com/53571625/109021742-7511e100-76bb-11eb-82b2-a7e07538420b.png)

**Comment by elikatsis** [comment]
This is not an error, this is a warning and it doesn't have to do with Kale.

Why is the pod stuck at `ContainerCreating` state? What is it waiting for? What events happened for this pod and the PVC it mounts?
You could `kubectl describe pod ...` to see the events on the pod, but they should be deleted by now (I think they remain for 15mins or so).
Maybe you could create a new run and try troubleshooting.

It sounds like a microk8s misconfiguration or a microk8s-on-GCP error.

**Comment by elikatsis** [comment]
@Soot3 this is not related to Kale, and I'd say it's not even related exactly to Kubeflow.

PTAL at https://github.com/kubeflow/kubeflow/issues/2347, I think it is relevant

**Comment by Soot3** [comment]
Thank you. Installing docker on the vm worked for me.
