### ISSUE TITLE
This step is in Pending state with this message: ErrImageNeverPull: Container image "argoproj/argoexec:v2.3.0" is not present with pull policy of Never

### ISSUE THREAD

**Issue by DataOx** [kubeflow-kale/kale#321]
I am trying to run the example on titanic-ml on local linux PC with miniKF installed. 

I am following the example here. Instead of using google cloud, I am using my local miniKF environment. https://codelabs.developers.google.com/codelabs/cloud-kubeflow-minikf-kale/#3

I am facing errors from the first step when create volume. Not sure why it needs to create volumn and how to fix this issue??

![image](https://user-images.githubusercontent.com/32042929/111540258-3679be80-876f-11eb-9047-c365678a73b8.png)

**Comment by elikatsis** [comment]
Hi @DataOx

It looks like docker ran out of space and started deleting images.
To fix this you can SSH into your VM and run
```
docker pull argoproj/argoexec:v2.3.0
```

You can SSH into your VM by `cd`ing into the corresponding Vagrant directory (where you've run `vagrant up`) and executing
```
vagrant ssh
```

**Comment by DataOx** [comment]
thanks @elikatsis . I can see that the image is there and there are quite some images. After some cleaning and followed your step, it still stucks there. how can I debug more?

**Comment by DataOx** [comment]
Now it works with some pruning and with your step. Thanks.
