### ISSUE TITLE
Kernel dying

### ISSUE THREAD

**Issue by Sebastian-Landl** [kubeflow-kale/kale#342]
I'm using `kubeflow` on `k3s` with a GPU and when running a bigger model with big data on this image ([gcr.io/arrikto-public/tensorflow-1.15.2-notebook-gpu](http://gcr.io/arrikto-public/tensorflow-1.15.2-notebook-gpu)) the kernel dies when the training begins.

However, when using this image ([gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-gpu](http://gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-gpu)) it worked just fine.

I'm going to try to fix this by creating an image with kale using a tensorflow 2.1.0 image as a base image for that. However, this is my first time creating a docker image, so I don't know how fast I'll be. And maybe this is not even the fix for that, I'll post an update here, unless someone else is faster with creating such an image.

**Comment by Sebastian-Landl** [comment]
I created an image with kale and tensorflow 2.4.1 which does not have this problem (https://hub.docker.com/r/slandl2/tensorflow-kale/tags?page=1&ordering=last_updated).

**Comment by palmoreck** [comment]
@Sebastian-Landl hi there

My team and I can't get working tensorflow >= 2.4.0 and kale >=0.6.1 . It would be really useful if you have a Dockerfile to have a look or some kind of steps to build the docker image `slandl2/tensorflow-kale:tensorflow-2.4.1-kale-notebook` Thanks for that :)

@StefanoFioravanzo @elikatsis thanks for `kubeflow-kale` has been really useful :) . Do you have a Dockerfile to install both tensorflow >= 2.4.0 and kale >=0.6.1 ?

Cheers 👋🏾

**Comment by Sebastian-Landl** [comment]
I can provide you with the Dockerfile I wrote:
```
###################
##     SETUP     ##
###################

FROM nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04

ENV HOME=/root
ENV NB_PREFIX=tensorflow-2.4.1-kale

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR $HOME
RUN apt update && apt -y upgrade && apt -y autoremove
RUN apt install -y wget nano git libhdf5-serial-dev curl pkg-config npm python3 python3-pip

##################
##   PACKAGES   ##
##################

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt

###################
##     KALE      ##
###################

# Install Kale from git
ENV KALE=$HOME/kale

RUN git clone https://github.com/kubeflow-kale/kale $HOME/kale

WORKDIR $KALE/backend
RUN pip3 install --upgrade .

WORKDIR $KALE/labextension
RUN npm install
RUN npm run build
RUN jupyter labextension install .

RUN jupyter lab build --dev-build=False --minimize=False

RUN rm -r $KALE

###################
##   EXECUTION   ##
###################

ENV NOTEBOOK_DIR=/home/jovyan
RUN mkdir -p $NOTEBOOK_DIR
WORKDIR $NOTEBOOK_DIR

EXPOSE 8888

CMD ["bash", "-c", "jupyter lab --notebook-dir=$NOTEBOOK_DIR --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=$NB_PREFIX"]
```

And you will also need the `requirements.txt`:
```
nodejs
tensorflow==2.4.1
matplotlib
trimesh
keras
enum34==1.1.8
jupyterlab>=2.0.0,<3.0.0
nbformat>=5.0
```

Best of luck with your efforts!

**Comment by palmoreck** [comment]
Thank you @Sebastian-Landl for your Dockerfile. Will definitely be really helpful :)

Best 👋🏾
