### ISSUE TITLE
An RPC Error has occurred: Method: kfp.upload_pipeline() |  Code: 6 (UnhandledError)

### ISSUE THREAD

**Issue by konsloiz** [kubeflow-kale/kale#372]
Hello everyone. I am trying to experiment with a local deployment of Kale and KFP avoiding using the usage of Kubeflow. 

What I did:
1. Deployed JupyterHub (Version 2.2.8) on local Kubernetes cluster
2. Deployed KFP standalone (Version 1.7.0) on the same local Kubernetes cluster
3. Installed Kale on JupyterLab 

However, when I am trying to "Compile and Run" I am getting an error during the "Uploading" phase:

> An RPC Error has occurred

> Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 OPR/78.0.4093.231

> Type: RPC

> Method: kfp.upload_pipeline()

> Code: 6 (UnhandledError)

> Transaction ID: 49pg627b0y

> Message: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/v1beta1/healthz (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))

> Details: You can find more information under /home/jovyan/kale.log

Any ideas?

**Comment by junaid18183** [comment]
I got the same issue, after researching it turns out that the `kfp.Client` is not able to connect with default host.
So I added the ENV in the jupyter notebook as below

`  env:
    - name: KF_PIPELINES_ENDPOINT
      value: http://ml-pipeline.kubeflow.svc.cluster.local:8888
`

**Comment by konsloiz** [comment]
@junaid18183 thanks for posting that here. This is also how we managed to solve it but forgot to close the issue. Maybe this will be useful for other users as well.
