### ISSUE TITLE
Kernel Error: ModuleNotFoundError: No module named 'kale.rpc'

### ISSUE THREAD

**Issue by Felihong** [kubeflow-kale/kale#43]
Hi there, 

after I updated my Dockerfile with the latest release:
```
RUN pip install kubeflow-kale
RUN jupyter labextension install kubeflow-kale-launcher
```
my connection to the notebook server is lost as I got `404: not found` error. 

So I tested locally by installing kale and kale extension:
```
jupyter labextension list        
                  
JupyterLab v1.1.4
Known labextensions:
   app dir: /Users/hong/.pyenv/versions/3.6.5/share/jupyter/lab
        kubeflow-kale-launcher v1.4.0  enabled  OK
```

However I got an error as below after calling `jupyter lab`
```
A Kernel Error has occurred
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0
Type: Kernel
Method: log.setup_logging()
Message: ModuleNotFoundError: No module named 'kale.rpc'
Details: [ "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m", "\u001b[0;31mModuleNotFoundError\u001b[0m Traceback (most recent call last)", "\u001b[0;32m<ipython-input-1-2f8b27adf4e0>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mkale\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrpc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mrun\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0m__kale_rpc_run\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m 2\u001b[0m \u001b[0m__kale_rpc_result\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m__kale_rpc_run\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"log.setup_logging\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'e30='\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'e30='\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n", "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'kale.rpc'" ]

```
Any ideas how could this happen? Thanks!

**Comment by elikatsis** [comment]
We use `pip3 install ...` in our Dockerfiles. Could you try that?

You may consult [these Dockerfiles](https://github.com/kubeflow-kale/kale/tree/master/docker/jupyterlab) that we've built and tested.
The `.dev` ones build images installing from the source code on `master` branches (or other branches, chosen via build arguments), while the non-`.dev` ones build images installing the latest releases.

**Comment by Felihong** [comment]
Hi @elikatsis , thanks for your reply. 

I now strongly speculate that there was something going wrong with my istio earlier today, as I just tested my image again and it works now, without any modifications. 

My apologize for troubling, and thanks for the enhancements! The `rok` storageClass warning is gone as well as you already pointed out.
