### ISSUE TITLE
Cell Metadata and Experiments not showing in Kale extension

### ISSUE THREAD

**Issue by tarun0** [kubeflow-kale/kale#45]
I'm installing Kale in _jupyter/tensorflow-notebook_ The cell tags are not showing in Kale UI. The behaviour of Kale is quite inconsistent as sometimes kale commands works just fine and other times it shows issue (perhaps) leading to experiments not being shown in the dropdown:
```
Traceback (most recent call last):
  File "/usr/local/bin/kale", line 7, in <module>
    from kale.command_line import main
  File "/usr/local/lib/python3.6/dist-packages/kale/command_line.py", line 2, in <module>
    import nbformat as nb
  File "/usr/local/lib/python3.6/dist-packages/nbformat/__init__.py", line 9, in <module>
    from ipython_genutils import py3compat
ModuleNotFoundError: No module named 'ipython_genutils'
```
`pip list` has one of its output as `ipython-genutils       0.2.0 ` Note the hiphen and underscore difference. 

I'm trying to setup Kale in Microk8s locally. The Jupyter version in the notebook version:
jupyter core     : 4.6.1
jupyter-notebook : 6.0.0
qtconsole        : not installed
ipython          : 7.10.1
ipykernel        : 5.1.3
jupyter client   : 5.3.3
jupyter lab      : 1.2.1
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

![Screenshot from 2020-01-24 12-38-59](https://user-images.githubusercontent.com/12914286/73054592-d233d580-3eb0-11ea-8eee-81e71a2510cc.png)

**Comment by elikatsis** [comment]
Hi @tarun0 ,

Could you provide some information regarding your Kale installation?
What commands did you use? What versions of Kale and kale extension did you install?

**Comment by tarun0** [comment]
@elikatsis Apparently, the error was because of ambiguity as a consequence of conda and pip environment. The details can be found here: https://stackoverflow.com/questions/59896133/cant-find-correct-directory-for-python-module/59896190#59896190

I got it to working by using Ubuntu base image instead of Jupyter which happened to have conda environment already and installing all the dependencies in it through pip only (as [manual installation of PyPi Kubeflow-kale package through skeleton](https://stackoverflow.com/questions/29286624/how-to-install-pypi-packages-using-anaconda-conda-command) didn't work). 

I was following the commands on blog only and I didn't specify any version. So, those should be latest: 0.4 for Kubeflow-kale, 1.4 for kale-extension and 0.2 for [celltags](https://github.com/jupyterlab/jupyterlab-celltags)

I was following the basic commands to install Jupyterlab 1.1.1 (assuming that Kale might have issues with other versions) and then `python3 -m pip install kubeflow-kale`
 `jupyter labextension install @jupyterlab/celltags` and 
`jupyter labextension install kubeflow-kale-launcher`

The only issues I am facing at this point using Kale with Kubeflow on Microk8s (single node cluster) is that Kale extension are:

1. Kale is still not showing Block, previous labels UI and I have to use celltags extension to manually input them. Please refer the image below.
2. The output (print statements) is sometimes not shown in the pipeline logs. It did work once; so, maybe I am missing something or maybe that isn't any issue yet. I'll try to run actual ML flow in it and then only, I can reach some conclusion.

![no tags](https://user-images.githubusercontent.com/12914286/73172521-3791fb80-4129-11ea-8616-cd4bee6d03f8.png)

![no log](https://user-images.githubusercontent.com/12914286/73172525-3bbe1900-4129-11ea-9dec-db6246780d7a.png)

**Comment by elikatsis** [comment]
1. We've completely refactored cell tagging. You can find a pencil icon on the top right of each cell. If you click this, a panel opens and you can set your step configurations. So, you shouldn't need `celltags`.
2. It's totally normal to not see output logs in this example you've shown. That is, because you **define** functions but you don't call them.
   If you executed the cells of your notebook, you wouldn't get any output by running the cells in the screenshot. You would have to execute `one()` in order to print `Hello!`:
   ```python
   def one():  # This is a definition, not a usage
       print("Hello!")

   one()  # This executes the function and leads to printing "Hello!"
   ```

**Comment by tarun0** [comment]
@elikatsis Ahh! Such a silly one from my side. Thanks anyway. And yeah, found the UI too. Thank you very much :) 

Just a question though - is there any plan to make a package for conda repo too?
