### ISSUE TITLE
Deploying models for inference?

### ISSUE THREAD

**Issue by wgmueller1** [kubeflow-kale/kale#49]
First off, thank you for your work on this project!   I was wondering if there is a roadmap for the kale project?   I'm specifically interested in how it might be possible to deploy models for inference using kale and Kubeflow.   Are there any active development discussion groups that are open to the public?

**Comment by StefanoFioravanzo** [comment]
Hello @wgmueller1 . We don't have a long term Roadmap yet. We are currently working on improving Kale's integration with Kubeflow Pipelines metadata and artifacts stores as well as running hyper parameter tuning and other exiting features.

We don't have short term plans for inference/serving, but any suggestion from your side would be very welcome. It would be of particular interest knowing your specific use case and how you envision you could use Kale + serving.

Thanks!

**Comment by wgmueller1** [comment]
Thanks for the response.
