### ISSUE TITLE
Instructions for setting up Kale on Kubeflow

### ISSUE THREAD

**Issue by vardhvish** [kubeflow-kale/kale#51]
I watched the session from Kubecon and want to use Kale for auto-generation of KF pipelines..

This is my setup currently.
- Azure Kubernetes Cluster (AKS) with two nodes
- Kubeflow 0.7.0 installed on top of AKS
- Created Notebook server on Kubeflow

I've a couple of follow up questions..
A) Will it be possible to use Kale under this setup ? What additional steps I should follow ?
B) Do I need to get JupyterLab instead of KF Notebook ? If yes, how do I connect that to Kubeflow, to run the pipelines ?

**Comment by elikatsis** [comment]
Hi @vardhvish,

To get Kale up and running you need a Notebook Server running JupyterLab, and have Kale & its Extension installed.
Please find Dockerfiles for such images in [this directory](https://github.com/kubeflow-kale/kale/tree/master/docker/jupyterlab).

You also need a default storage class that is able to provision `ReadWriteMany` (also called `RWX`) PVCs.
I don't have any experience on Azure, but I find that `AzureFile` supports `RWX`. So you should be able to do that ([source](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)).

**Comment by vardhvish** [comment]
Thanks for the response Ilias.. I'll try out the steps you mentioned..

**Comment by vardhvish** [comment]
Just want to give an update.. I was able to pick a docker file from this repo, build an image & use it to create a JL notebook server.. 

But since the default StorageClass in the underlying AKS cluster was AzureDisk, the PVC failed with the error -
**Warning  ProvisioningFailed  34s (x63 over 125m)  persistentvolume-controller  Failed to provision volume with StorageClass "default": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported**

Trying to create a new PVC with AzureFile as StorageClass on the AKS cluster was unfortunately not supported, per company policy.. 

So I've to leave out the Kale+JL-notebook option for now..

**Comment by shivangicloud04** [comment]
@vardhvish Were you able to workout kale on aks as I am facing the same issue? If not , was kf pipelines worked as an alternative?

**Comment by ca-scribner** [comment]
I've got a similar issue.  I'd like to use Kale on a k8s cluster that has a default storage class that is only RWO.  Ideally a good fix would be being able to select a different storage class from the kale extension UI
