### ISSUE TITLE
Pipeline steps base image

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow-kale/kale#6]
Currently Kale uses the KFP default base image when executing pipeline steps.

The alternative could be to use the NotebookServer image.

A user running a Notebook and testing some code, is working on the env defined by the Notebook Server image. If we snapshot and mount the workspace to preserve the user environment, then it is reasonable to run the steps on the same image where the user develops the notebook.

It is not enough to use the default Kale Notebook Server image, as users might extend this image with custom images that add some custom packages.

The approach explained in #3 could be used to retrieve the image of the current container when Kale is executed in the NotebookServer.

**Comment by StefanoFioravanzo** [comment]
@elikatsis  what do you think about the following approach to retrieve the docker image used from inside the Notebook Server:

- Use env variable `HOSTNAME` to filter the current `pod` from `kubectl get pods -o json` output
- Use env variable `NB_PREFIX` (the string after the last `/`) to filter the notebook server container, and then its image.

Is it reliable to use `NB_PREFIX` as the name of the current container? You can see how I would do this in #3

**Comment by elikatsis** [comment]
@StefanoFioravanzo,

I would propose using Kubernetes Client to get all the required information, instead of calling CLI commands.

Please take a look at @klolos'  script [in this commit](https://github.com/arrikto/kale/commit/ce1f7cfd744f22327f060c86955c14985407a4fe), retrieving Notebook's PVCs, as an example on Kubernetes API usage.

**Comment by StefanoFioravanzo** [comment]
@elikatsis nice work there. I think we could just extend the script with a function `_get_container_base_image` and include this python script in the `utils` folder.

If you do that, then I can update PR #10 to just call that function.
