### ISSUE TITLE
Jupyterlab 2.0.1 support?

### ISSUE THREAD

**Issue by sukratkashyap** [kubeflow-kale/kale#99]
Hi,

Just wanted to know are there any plans for kubeflow-kale-launcher for JupyterLab version 2.0.1?

**Comment by StefanoFioravanzo** [comment]
Hi @sukrat-kashyap yes definitely we want to support it. There have been some major changes to how JP extensions are build starting from version, so currently we support up to <2.0.0. But we will upgrade soon.

**Comment by sylus** [comment]
Was curious if this would be on the short term radar? Our kubeflow environment is all using the newest jupyterlab due to some requirements and really wanted to give Kale a spin since heard great things :D

**Comment by DavidSpek** [comment]
I have added a broken draft pull request in an attempt to add support for Jupyterlab 2.x. It will need some TLC from an actual developer I am guessing, but I will also continue to try and get it working.
